# Generated by Django 4.0.5 on 2022-06-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='User', max_length=20)),
                ('image', models.ImageField(upload_to='static')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(max_length=150)),
            ],
        ),
    ]
